spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 143352206371-qenhe2j7l9kmnsbtee83h7mk1rknmgma.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret: mysecretkeyz1a4s5x2jeong1029384756jwthashkey123098
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8080