

### 전체 사진 가져오기
GET http://localhost:8080/api/v1/photo-entries
Authorization: Bearer {{token}}
Content-Type: application/json

### id로 사진 가져오기
GET http://localhost:8080/api/v1/photo-entries/1
Authorization: Bearer {{token}}
Content-Type: application/json

### 범위 내의 사진 가져오기
GET http://localhost:8080/api/v1/photo-entries?swLat=37&swLng=126&neLat=38&neLng=128
Authorization: Bearer {{token}}
Content-Type: application/json

### native query 범위 내의 사진 가져오기
GET http://localhost:8080/api/v1/photo-entries/native?swLat=37&swLng=126&neLat=38&neLng=128
Authorization: Bearer {{token}}
Content-Type: application/json

### 친구 사진id로 사진 가져오기
GET http://localhost:8080/api/v1/users/1/photo-entries/1
Authorization: Bearer {{token}}
Content-Type: application/json

### 친구 사진 가져오기
GET http://localhost:8080/api/v1/users/1/photo-entries?swLat=37.4453022&swLng=126.9158586&neLat=37.6875009&neLng=127.0401414&level=12
Authorization: Bearer {{token}}
Content-Type: application/json

### 집계 데이터 가져오기
GET http://localhost:8080/api/v1/photo-entries/statistics/province
Authorization: Bearer {{token}}
Content-Type: application/json